kind: Job
apiVersion: batch/v1
metadata: 
  name: demo-job
  namespace: nginx
spec:
  completions: 3
  parallelism: 2

  template:
    metadata:
      labels:
        app: batch-task

    spec:
      containers:
      - name: batch-container
        image: busybox:latest
        command: ["sh", "-c", "echo Cron active && sleep 10", ]
      restartPolicy: Never
